#include "parser.h"
#include "log.h"

const char *
ast_expression_to_str(struct ast_expression *expression)
{
#define TRANSLATE(e) case e: return #e;
	switch (expression->type) {
		TRANSLATE(EXPRESSION_NONE);
		TRANSLATE(EXPRESSION_ASSIGNMENT);
		TRANSLATE(EXPRESSION_CONDITION);
		TRANSLATE(EXPRESSION_OR);
		TRANSLATE(EXPRESSION_AND);
		TRANSLATE(EXPRESSION_EQUALITY);
		TRANSLATE(EXPRESSION_RELATION);
		TRANSLATE(EXPRESSION_ADDITION);
		TRANSLATE(EXPRESSION_MULTIPLICATION);
		TRANSLATE(EXPRESSION_UNARY);
		TRANSLATE(EXPRESSION_SUBSCRIPT);
		TRANSLATE(EXPRESSION_FUNCTION);
		TRANSLATE(EXPRESSION_METHOD);
		TRANSLATE(EXPRESSION_IDENTIFIER);
		TRANSLATE(EXPRESSION_STRING);
		TRANSLATE(EXPRESSION_ARRAY);
		TRANSLATE(EXPRESSION_BOOL);
	default:
		LOG_W(log_misc, "unknown token");
		break;
	}
#undef TRANSLATE
	return "";
}
