#include "ninja.h"
#include "parse.h"
#include "log.h"

#include <string.h>
#include <stdio.h>
#include <sys/stat.h>

#define PATH_MAX 4096

static void
write_header(FILE *file)
{
	fprintf(file, "# This file is generated by boson %s\n", VERSION);
	fprintf(file, "# Do not edit by hand\n");

	fprintf(file, "\nninja_required_version = 1.9.0\n");
}

int
emit_ninja(struct node_root *root, const char *build_dir)
{
	if (mkdir(build_dir, 0775) == -1) {
		report("Build directory already configured");
		return 1;
	}
	info("Build dir: %s", build_dir);

	char ninja_path[PATH_MAX] = {0};
	sprintf(ninja_path, "%s/build.ninja", build_dir);

	FILE *ninja = fopen(ninja_path, "w");
	if (!ninja) {
		report("failed to create build.ninja");
		return 1;
	}

	write_header(ninja);

	fclose(ninja);
	return 0;
}
