#include "token.h"
#include "log.h"

const char *
token_to_string(struct token *token)
{
#define TOKEN_TRANSLATE(e) case e: return #e;
	switch (token->type) {
	TOKEN_TRANSLATE(TOKEN_EOF);
	TOKEN_TRANSLATE(TOKEN_EOL);
	TOKEN_TRANSLATE(TOKEN_LPAREN);
	TOKEN_TRANSLATE(TOKEN_RPAREN);
	TOKEN_TRANSLATE(TOKEN_LBRACK);
	TOKEN_TRANSLATE(TOKEN_RBRACK);
	TOKEN_TRANSLATE(TOKEN_LCURL);
	TOKEN_TRANSLATE(TOKEN_RCURL);
	TOKEN_TRANSLATE(TOKEN_DOT);
	TOKEN_TRANSLATE(TOKEN_COMMA);
	TOKEN_TRANSLATE(TOKEN_COLON);
	TOKEN_TRANSLATE(TOKEN_ASSIGN);
	TOKEN_TRANSLATE(TOKEN_PLUS);
	TOKEN_TRANSLATE(TOKEN_MINUS);
	TOKEN_TRANSLATE(TOKEN_STAR);
	TOKEN_TRANSLATE(TOKEN_SLASH);
	TOKEN_TRANSLATE(TOKEN_MODULO);
	TOKEN_TRANSLATE(TOKEN_PLUSEQ);
	TOKEN_TRANSLATE(TOKEN_MINUSEQ);
	TOKEN_TRANSLATE(TOKEN_STAREQ);
	TOKEN_TRANSLATE(TOKEN_SLASHEQ);
	TOKEN_TRANSLATE(TOKEN_MODULOEQ);
	TOKEN_TRANSLATE(TOKEN_EQ);
	TOKEN_TRANSLATE(TOKEN_NEQ);
	TOKEN_TRANSLATE(TOKEN_GT);
	TOKEN_TRANSLATE(TOKEN_GEQ);
	TOKEN_TRANSLATE(TOKEN_LT);
	TOKEN_TRANSLATE(TOKEN_LEQ);
	TOKEN_TRANSLATE(TOKEN_TRUE);
	TOKEN_TRANSLATE(TOKEN_FALSE);
	TOKEN_TRANSLATE(TOKEN_IF);
	TOKEN_TRANSLATE(TOKEN_ELSE);
	TOKEN_TRANSLATE(TOKEN_ELIF);
	TOKEN_TRANSLATE(TOKEN_ENDIF);
	TOKEN_TRANSLATE(TOKEN_AND);
	TOKEN_TRANSLATE(TOKEN_OR);
	TOKEN_TRANSLATE(TOKEN_NOT);
	TOKEN_TRANSLATE(TOKEN_FOREACH);
	TOKEN_TRANSLATE(TOKEN_ENDFOREACH);
	TOKEN_TRANSLATE(TOKEN_IN);
	TOKEN_TRANSLATE(TOKEN_CONTINUE);
	TOKEN_TRANSLATE(TOKEN_BREAK);
	TOKEN_TRANSLATE(TOKEN_IDENTIFIER);
	TOKEN_TRANSLATE(TOKEN_STRING);
	TOKEN_TRANSLATE(TOKEN_NUMBER);
	default:
		report("unknown token");
		break;
	}
#undef TOKEN_TRANSLATE
	return "";
}
